"use client";

import type { PartRecord, TankModel } from "../../src/tank/model";
import { coneDevelopment, roofPanelCutGeometry, roofPanelLayout } from "../../src/calculations/roof";
import { roofSupportGeometry } from "../../src/calculations/roofSupport";
import { shellPanels, shellPlateCountPerCourse } from "../../src/calculations/shell";
import { stairGeometry } from "../../src/calculations/stair";
import { capacityTable, totalCapacity } from "../../src/calculations/capacity";

const polar=(cx:number,cy:number,r:number,a:number)=>[cx+r*Math.cos(a),cy+r*Math.sin(a)] as const;
const points=(rows:readonly (readonly [number,number])[])=>rows.map(row=>row.join(",")).join(" ");
const arcPath=(cx:number,cy:number,r:number,a:number,mid=-Math.PI/2)=>{const p1=polar(cx,cy,r,mid-a/2),p2=polar(cx,cy,r,mid+a/2);return `M ${p1[0]} ${p1[1]} A ${r} ${r} 0 0 1 ${p2[0]} ${p2[1]}`};
const sectorPath=(cx:number,cy:number,ro:number,ri:number,a:number,mid=-Math.PI/2)=>{const p1=polar(cx,cy,ro,mid-a/2),p2=polar(cx,cy,ro,mid+a/2),p3=polar(cx,cy,ri,mid+a/2),p4=polar(cx,cy,ri,mid-a/2);return `M ${p1[0]} ${p1[1]} A ${ro} ${ro} 0 0 1 ${p2[0]} ${p2[1]} L ${p3[0]} ${p3[1]} A ${ri} ${ri} 0 0 0 ${p4[0]} ${p4[1]} Z`};

function FitText({x,y,width,value,className,fontSize}:{x:number;y:number;width:number;value:string|number;className:string;fontSize?:number}){
  const label=String(value),size=fontSize??7.5;
  const estimated=[...label].reduce((sum,char)=>sum+(char.charCodeAt(0)>255?size:size*.62),0);
  const squeeze=estimated>width;
  return <text x={x} y={y} className={className} style={fontSize?{fontSize}:undefined} textLength={squeeze?width:undefined} lengthAdjust={squeeze?"spacingAndGlyphs":undefined}>{label}</text>;
}

function TitleBlock({model,title}:{model:TankModel;title:string}){
  return <div className="titleblock"><div><small>项目</small><b>{model.project.name}</b></div><div><small>图名</small><span>{title}</span></div><div><small>图号</small><span>{model.project.drawingNo}</span></div><div><small>单位</small><span>mm</span></div><div><small>版本</small><span>{model.project.revision}</span></div><div><small>状态</small><span>初步设计 / 未校核</span></div></div>;
}

export function RoofDevelopment({model,selectedId}:{model:TankModel;selectedId:string}){
  const development=coneDevelopment(model),panels=roofPanelLayout(model),courses=Math.max(1,Math.round(model.roof.radialCourseCount??1));
  const selectedSector=Number(selectedId.match(/^RP-(\d+)/)?.[1]??1);
  const sector=Math.max(1,Math.min(model.roof.plateCount,selectedSector));
  const sectorPanels=panels.filter(item=>item.sector===sector);
  const selectedCourse=Number(selectedId.match(/^RP-\d+-(\d+)/)?.[1]??1);
  const displayPanels=[...sectorPanels].reverse().map(panel=>({panel,cut:roofPanelCutGeometry(model,panel)}));
  const cx=175,cy=350,scale=230/development.slantLength,outer=development.slantLength*scale,inner=Math.max(2,development.innerRadius*scale);
  const pieceGap=14,pieceHeight=Math.min(68,(250-pieceGap*(courses-1))/courses),pieceScale=pieceHeight/Math.max(1,...displayPanels.map(item=>item.cut.cutRadialLength)),rightX=535,rightTop=72;
  const wholeArea=sectorPanels.reduce((sum,item)=>sum+item.exactArea,0)/1e6;
  const seamType=model.roof.seamType??"lap",seamText=seamType==="lap"?`单面搭接焊 · 搭接 ${model.roof.lapAllowance.toFixed(0)} mm`:"对接焊 · 间隙/坡口按 WPS";
  const outerLeft=polar(cx,cy,outer,-Math.PI/2-development.plateAngleRad/2),outerRight=polar(cx,cy,outer,-Math.PI/2+development.plateAngleRad/2),innerLeft=polar(cx,cy,inner,-Math.PI/2-development.plateAngleRad/2),innerRight=polar(cx,cy,inner,-Math.PI/2+development.plateAngleRad/2);
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>RP-{String(sector).padStart(2,"0")} · 完整瓜皮与 {courses} 段分块展开</b><span>{model.roof.plateCount} 瓣 × 每瓣 {courses} 段 = {panels.length} 块顶板</span></div><svg viewBox="0 0 760 430" className="engineering-svg">
    <text x="58" y="35" className="note strong">A. 一整片瓜皮的理论展开（组装关系）</text><text x="58" y="53" className="dimtext">总斜长 {(development.slantLength-development.innerRadius).toFixed(1)} mm</text>
    <line x1="58" y1="70" x2="84" y2="70" className="roof-radial-weld"/><text x="90" y="73" className="roof-legend">J-R 径向瓣缝</text><line x1="180" y1="70" x2="206" y2="70" className="roof-circ-weld"/><text x="212" y="73" className="roof-legend">J-C 环向分段缝</text><line x1="58" y1="85" x2="84" y2="85" className="roof-cut-outline"/><text x="90" y="88" className="roof-legend">含搭接/余量的下料轮廓</text>
    <path d={sectorPath(cx,cy,outer,inner,development.plateAngleRad)} className="roof-whole"/>
    <line x1={outerLeft[0]} y1={outerLeft[1]} x2={innerLeft[0]} y2={innerLeft[1]} className="roof-radial-weld"/><line x1={outerRight[0]} y1={outerRight[1]} x2={innerRight[0]} y2={innerRight[1]} className="roof-radial-weld"/>
    {sectorPanels.slice(0,-1).map((item,index)=>{const radius=item.outerRadius*scale,p=polar(cx,cy,radius,-Math.PI/2+development.plateAngleRad/2);return <g key={item.id}><path d={arcPath(cx,cy,radius,development.plateAngleRad)} className="roof-circ-weld"/><text x={p[0]+8} y={p[1]+3} className="roof-seam-id">J-C{index+1}</text></g>})}
    {sectorPanels.map((item,index)=>{const midRadius=(item.innerRadius+item.outerRadius)*.5*scale,p=polar(cx,cy,midRadius,-Math.PI/2);return <g key={item.id}><circle cx={p[0]} cy={p[1]} r="10" className={selectedCourse===item.course?"roof-index selected":"roof-index"}/><text x={p[0]} y={p[1]+3} textAnchor="middle" className="roof-index-text">{index+1}</text></g>})}
    <text x="320" y="195" className="split-arrow">→</text><text x="302" y="216" className="note">沿径向拼缝拆开</text>
    <text x="410" y="35" className="note strong">B. 实际分别下料的 {courses} 块</text><text x="410" y="53" className="roof-seam-note">接缝：{seamText}</text>
    <line x1="395" y1="75" x2="395" y2="314" className="roof-direction"/><polygon points="390,306 400,306 395,318" className="roof-direction-arrow"/><text x="362" y="67" className="roof-direction-text">罐壁外缘</text><text x="366" y="336" className="roof-direction-text">中心孔</text>
    {displayPanels.map(({panel:item,cut},index)=>{const y=rightTop+index*(pieceHeight+pieceGap),ch=cut.cutRadialLength*pieceScale,ciw=cut.cutInnerChord*pieceScale,cow=cut.cutOuterChord*pieceScale,netTop=y+(cut.cutOuterRadius-item.outerRadius)*pieceScale,nh=item.radialLength*pieceScale,iw=item.innerChord*pieceScale,ow=item.outerChord*pieceScale,labelX=rightX+Math.max(ciw,cow)/2+12,isSelected=selectedCourse===item.course;return <g key={item.id} className={isSelected?"roof-piece selected":"roof-piece"}><polygon className="roof-cut-outline" points={points([[rightX-cow/2,y],[rightX+cow/2,y],[rightX+ciw/2,y+ch],[rightX-ciw/2,y+ch]])}/><polygon className="roof-net-shape" points={points([[rightX-ow/2,netTop],[rightX+ow/2,netTop],[rightX+iw/2,netTop+nh],[rightX-iw/2,netTop+nh]])}/><line x1={rightX-ow/2} y1={netTop} x2={rightX-iw/2} y2={netTop+nh} className="roof-radial-weld"/><line x1={rightX+ow/2} y1={netTop} x2={rightX+iw/2} y2={netTop+nh} className="roof-radial-weld"/>{item.course<courses&&<line x1={rightX-ow/2} y1={netTop} x2={rightX+ow/2} y2={netTop} className="roof-circ-weld"/>}{item.course>1&&<line x1={rightX-iw/2} y1={netTop+nh} x2={rightX+iw/2} y2={netTop+nh} className="roof-circ-weld"/>}<text x={labelX} y={y+12} className="note strong">{item.id}</text><text x={labelX} y={y+27} className="dimtext">下料 外 {cut.cutOuterChord.toFixed(0)} / 内 {cut.cutInnerChord.toFixed(0)}</text><text x={labelX} y={y+41} className="dimtext">切长 {cut.cutRadialLength.toFixed(0)} · 环搭 {cut.outerLap.toFixed(0)}</text><text x={labelX} y={y+55} className="roof-legend">净 外 {item.outerChord.toFixed(0)} / 内 {item.innerChord.toFixed(0)} × {item.radialLength.toFixed(0)}</text><text x={rightX} y={netTop+nh/2+3} textAnchor="middle" className="plateid">第 {item.course} 段</text></g>})}
    <g transform="translate(58 374)"><text className="note">J-R 为相邻瓜皮之间的径向接缝；J-C 为同一瓜皮各段之间的环向接缝。</text><text y="20" className="note">搭接时由高位（靠中心）板覆盖低位板；每瓣顺时针侧拥有一条径向搭接。净面积 {wholeArea.toFixed(4)} m²。</text><text y="40" className="note warn">橙色虚线才是制造下料轮廓；焊脚、坡口、错边及焊接顺序仍需按 WPS/正式制造图确定。</text></g>
  </svg><TitleBlock model={model} title="完整瓜皮及径向分段展开图"/></div></div>;
}

export function RoofStructure({model}:{model:TankModel}){
  const support=roofSupportGeometry(model);
  const cx=175,cy=174,r=112,ex=415,ey=220,ew=270,eh=125,courses=Math.max(1,Math.round(model.roof.radialCourseCount??1));
  const bayAngle=360/support.rafterCount;
  const tableX=52,tableY=306,rowH=20,tableW=656;
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>支承锥顶结构布置图</b><span>中心柱 + 径向椽梁 + 环向梁 · 初步布置</span></div><svg viewBox="0 0 760 430" className="engineering-svg">
    <circle cx={cx} cy={cy} r={r} className="outline"/>{Array.from({length:model.roof.plateCount},(_,i)=>{const a=(i+.5)*2*Math.PI/model.roof.plateCount,p=polar(cx,cy,r,a);return <line key={i} x1={cx} y1={cy} x2={p[0]} y2={p[1]} className="roof-plan-seam"/>})}{Array.from({length:courses-1},(_,i)=><circle key={i} cx={cx} cy={cy} r={r*(i+1)/courses} className="roof-plan-seam"/>)}<circle cx={cx} cy={cy} r="8" className="support-member"/>
    {Array.from({length:support.rafterCount},(_,i)=>{const a=i*2*Math.PI/support.rafterCount,p=polar(cx,cy,r,a);return <line key={i} x1={cx} y1={cy} x2={p[0]} y2={p[1]} className="support-member"/>})}
    {support.ringRadii.map(radius=><circle key={radius} cx={cx} cy={cy} r={radius/(model.diameter/2)*r} className="support-ring"/>)}
    <text x="52" y="28" className="note strong">A. 骨架俯视中心线放样</text><text x="52" y="45" className="note">椽梁 {support.rafterCount} 根 · 等分角 {bayAngle.toFixed(3)}° · 环梁 {support.rings.length} 道</text><line x1="52" y1="59" x2="78" y2="59" className="support-member"/><text x="84" y="62" className="roof-legend">椽梁（直）</text><line x1="142" y1="59" x2="168" y2="59" className="support-ring"/><text x="174" y="62" className="roof-legend">环梁（弯）</text>
    <line x1={cx-r} y1={cy+r+14} x2={cx+r} y2={cy+r+14} className="dim"/><text x={cx-28} y={cy+r+29} className="dimtext">Ø{model.diameter.toFixed(0)}</text>
    {support.rings.map((ring,index)=>{const rr=ring.radius/(model.diameter/2)*r,angle=-Math.PI/4,p=polar(cx,cy,rr,angle);return <g key={ring.id}><line x1={p[0]} y1={p[1]} x2={278} y2={93+index*18} className="support-leader"/><text x="282" y={96+index*18} className="roof-legend">{ring.id}  R{ring.radius.toFixed(0)}</text></g>})}
    <line x1={ex} y1={ey} x2={ex+ew/2} y2={ey-eh} className="outline"/><line x1={ex+ew/2} y1={ey-eh} x2={ex+ew} y2={ey} className="outline"/><line x1={ex} y1={ey} x2={ex+ew} y2={ey} className="dim"/>
    <line x1={ex+ew/2} y1={ey-eh+5} x2={ex+ew/2} y2={ey} className="support-column"/>
    {support.ringRadii.map(radius=>{const ratio=radius/(model.diameter/2),dx=ew/2*ratio,y=ey-eh*(1-ratio);return <g key={radius}><circle cx={ex+ew/2-dx} cy={y} r="4" className="support-ring"/><circle cx={ex+ew/2+dx} cy={y} r="4" className="support-ring"/></g>})}
    <text x={ex} y="28" className="note strong">B. 径向剖面与直料尺寸</text><text x={ex} y="47" className="note">屋面坡度 {(support.slopeAngleRad*180/Math.PI).toFixed(3)}°（1:{(model.diameter/2/model.roof.rise).toFixed(3)}）</text><text x={ex} y="64" className="note">椽梁中心线：直料 L={support.rafterSlopingLength.toFixed(1)}，不弯曲</text><text x={ex} y="81" className="note">中心柱：Ø{support.centerColumnDiameter.toFixed(0)} · H≈{support.centerColumnHeight.toFixed(1)}</text>
    <line x1={ex-8} y1={ey+20} x2={ex+ew+8} y2={ey+20} className="dim"/><text x={ex+ew/2-40} y={ey+35} className="dimtext">水平投影 {model.diameter.toFixed(0)}</text>
    <text x={ex} y="270" className="roof-legend">椽梁分跨斜长：{support.rafterSpans.map(span=>`S${span.index}=${span.slopingLength.toFixed(0)}`).join(" · ")} mm</text>
    <rect x={tableX} y={tableY} width={tableW} height={rowH*(support.rings.length+1)} className="support-table-box"/>
    {[tableX+74,tableX+153,tableX+235,tableX+330,tableX+435,tableX+545].map(x=><line key={x} x1={x} y1={tableY} x2={x} y2={tableY+rowH*(support.rings.length+1)} className="support-table-line"/>)}
    {Array.from({length:support.rings.length},(_,i)=><line key={i} x1={tableX} y1={tableY+rowH*(i+1)} x2={tableX+tableW} y2={tableY+rowH*(i+1)} className="support-table-line"/>)}
    <text x={tableX} y={tableY-8} className="note strong">C. 环梁中心线弯制 / 分段放样表</text>
    {[["编号",tableX,tableX+74],["半径 R",tableX+74,tableX+153],["标高 EL",tableX+153,tableX+235],["整圈周长",tableX+235,tableX+330],["每跨圆弧料长",tableX+330,tableX+435],["直段弦长",tableX+435,tableX+545],["数量",tableX+545,tableX+tableW]].map(([label,left,right])=><FitText key={String(label)} x={Number(left)+8} y={tableY+14} width={Number(right)-Number(left)-14} value={String(label)} className="support-table-head" fontSize={7}/>)}
    {support.rings.map((ring,index)=>{const y=tableY+rowH*(index+1)+14,cells:[string|number,number,number][]=[[ring.id,tableX,tableX+74],[ring.radius.toFixed(1),tableX+74,tableX+153],[`+${ring.elevation.toFixed(1)}`,tableX+153,tableX+235],[ring.circumference.toFixed(1),tableX+235,tableX+330],[ring.bayArcLength.toFixed(1),tableX+330,tableX+435],[ring.bayChord.toFixed(1),tableX+435,tableX+545],[`${ring.bayCount} 跨`,tableX+545,tableX+tableW]];return <g key={ring.id}>{cells.map(([value,left,right],cell)=><FitText key={cell} x={left+8} y={y} width={right-left-14} value={value} className="support-table-text"/>)}</g>})}
    <text x="52" y="397" className="note">弯制方案：型钢按表中 R 冷弯/卷弯，单跨中心线圆弧料长用于弯料放样；若改用直段折线，则采用“直段弦长”。</text><text x="52" y="415" className="note warn">以上不含端切、接头及焊缩余量；构件截面、接头位置、拼接数量、滚弯回弹和顶板连接必须由正式结构计算与制造图确定。</text>
  </svg><TitleBlock model={model} title="支承锥顶结构布置图"/></div></div>;
}

export function StairDetail({model}:{model:TankModel}){
  const stair=stairGeometry(model);
  const pcx=135,pcy=155,tankR=72,start=model.stair.startAngle*Math.PI/180,planScale=tankR/(model.diameter/2);
  const supportStep=Math.max(1,Math.ceil(stair.supportFrames.length/12));
  const devX=285,devY=238,devW=230,devH=150,maxDev=stair.outerRadius*stair.overallAngleRad;
  const bracketX=576,bracketY=184,tableX=50,tableY=292,rowH=Math.min(20,72/(stair.flights.length+1)),tableW=660,tableH=rowH*(stair.flights.length+1);
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>外侧螺旋楼梯设计详图</b><span>平面定位 + 梯梁展开 + 罐壁支撑架</span></div><svg viewBox="0 0 760 430" className="engineering-svg">
    <circle cx={pcx} cy={pcy} r={tankR} className="outline"/>{stair.flights.map(flight=>{const innerPath=Array.from({length:55},(_,i)=>polar(pcx,pcy,stair.innerRadius*planScale,flight.startAngleRad+flight.angleRad*i/54)),outerPath=Array.from({length:55},(_,i)=>polar(pcx,pcy,stair.outerRadius*planScale,flight.startAngleRad+flight.angleRad*i/54));return <g key={flight.id}><polyline points={points(innerPath)} className="stair-stringer-inner"/><polyline points={points(outerPath)} className="stair-stringer-outer"/></g>})}
    {[...stair.platforms,stair.topPlatform].map(platform=>{const p=polar(pcx,pcy,stair.centerRadius*planScale,platform.centerAngleRad),w=platform.width*planScale,l=platform.length*planScale,deg=platform.centerAngleRad*180/Math.PI;return <rect key={platform.id} x={p[0]-w/2} y={p[1]-l/2} width={w} height={l} transform={`rotate(${deg} ${p[0]} ${p[1]})`} className="stair-platform-plan"/>})}
    {Array.from({length:Math.min(stair.stepCount,42)},(_,i)=>{const count=Math.min(stair.stepCount,42),index=Math.round(i*(stair.stepCount-1)/Math.max(1,count-1)),a=start+stair.deltaAngleRad*index,p1=polar(pcx,pcy,stair.innerRadius*planScale,a),p2=polar(pcx,pcy,stair.outerRadius*planScale,a);return <line key={i} x1={p1[0]} y1={p1[1]} x2={p2[0]} y2={p2[1]} className="weld"/>})}
    {stair.supportFrames.filter((_,i)=>i%supportStep===0).map(frame=>{const p1=polar(pcx,pcy,tankR,frame.angleRad),p2=polar(pcx,pcy,stair.outerRadius*planScale,frame.angleRad);return <line key={frame.index} x1={p1[0]} y1={p1[1]} x2={p2[0]} y2={p2[1]} className="stair-support-plan"/>})}
    <text x="50" y="28" className="note strong">A. 平面螺旋定位</text><text x="50" y="46" className="note">R内 {stair.innerRadius.toFixed(0)} · R中 {stair.centerRadius.toFixed(0)} · R外 {stair.outerRadius.toFixed(0)}</text><text x="50" y="64" className="note">{stair.flights.length} 梯段 · {stair.platforms.length} 中间平台 · {stair.direction===1?"逆时针":"顺时针"}上升 · 占角 {(stair.overallAngleRad*180/Math.PI).toFixed(2)}°</text><line x1="50" y1="79" x2="76" y2="79" className="stair-support-plan"/><text x="82" y="82" className="roof-legend">罐壁支撑架</text>
    <text x={devX} y="28" className="note strong">B. 各梯段圆柱面展开（平台处断开）</text><text x={devX} y="46" className="note">梯梁在休息平台处收头；每段按本页梯段表单独滚弯、预拼和吊装</text>
    <text x={devX} y="64" className="roof-legend">内梯梁合计 L={stair.stringers[0].helixLength.toFixed(1)}</text><text x={devX} y="77" className="roof-legend">外梯梁合计 L={stair.stringers[1].helixLength.toFixed(1)}</text>
    {stair.stringers.map((stringer,index)=>{const cls=index===0?"stair-stringer-inner":"stair-stringer-outer",offset=index*6,progress=(angle:number)=>(angle-start)*stair.direction;return <g key={stringer.side}>{stair.flights.map(flight=>{const x1=devX+devW*(stringer.radius*progress(flight.startAngleRad))/maxDev,x2=devX+devW*(stringer.radius*progress(flight.endAngleRad))/maxDev,y1=devY-devH*flight.startElevation/model.shellHeight-offset,y2=devY-devH*flight.endElevation/model.shellHeight-offset;return <g key={flight.id}><line x1={x1} y1={y1} x2={x2} y2={y2} className={cls}/>{index===1&&<text x={(x1+x2)/2+3} y={(y1+y2)/2-4} className="stair-flight-id">{flight.id}</text>}</g>})}{stair.platforms.map(platform=>{const x1=devX+devW*(stringer.radius*progress(platform.startAngleRad))/maxDev,x2=devX+devW*(stringer.radius*progress(platform.endAngleRad))/maxDev,y=devY-devH*platform.elevation/model.shellHeight-offset;return <line key={platform.id} x1={x1} y1={y} x2={x2} y2={y} className="stair-platform-developed"/>})}</g>})}
    <line x1={devX-12} y1={devY} x2={devX-12} y2={devY-devH-8} className="dim"/><text x={devX-56} y={devY-devH/2} className="dimtext">H {model.shellHeight.toFixed(0)}</text><text x={devX} y={devY+18} className="stair-fab-note">斜线只是圆柱展开后的中心线，不是从整张钢板斜切</text><text x={devX} y={devY+34} className="stair-fab-step">直条下料 → 分段划点 → 滚弯到 R 并在胎架逐点抬高 → 平台处收头</text>
    <text x="566" y="28" className="note strong">C. 平台与罐壁支撑架剖面</text><path d={`M ${bracketX} 75 Q ${bracketX-10} 145 ${bracketX} 235`} className="outline"/><line x1={bracketX} y1={bracketY} x2="700" y2={bracketY} className="stair-support-beam"/><line x1={bracketX} y1={bracketY+50} x2="700" y2={bracketY} className="stair-support-brace"/><rect x={bracketX+8} y={bracketY-7} width="124" height="7" className="stair-support-tread"/><line x1="700" y1={bracketY} x2="700" y2="105" className="stair-platform-rail"/><line x1="700" y1="105" x2="665" y2="105" className="stair-platform-rail"/><text x="590" y="70" className="roof-legend">罐壁垫板/连接板</text><text x="655" y="96" className="roof-legend">平台扶手 H{model.stair.handrailHeight}</text><text x="590" y="202" className="roof-legend">两道径向横梁</text><text x="590" y="250" className="roof-legend">斜撑</text><line x1={bracketX} y1="268" x2="700" y2="268" className="dim"/><text x="598" y="283" className="dimtext">伸出 {model.stair.clearance+model.stair.width} mm</text>
    <rect x={tableX} y={tableY} width={tableW} height={tableH} className="support-table-box"/>{[tableX+62,tableX+166,tableX+224,tableX+294,tableX+390,tableX+486,tableX+560].map(x=><line key={x} x1={x} y1={tableY} x2={x} y2={tableY+tableH} className="support-table-line"/>)}{Array.from({length:stair.flights.length},(_,i)=><line key={i} x1={tableX} y1={tableY+rowH*(i+1)} x2={tableX+tableW} y2={tableY+rowH*(i+1)} className="support-table-line"/>)}
    {[["梯段",tableX,tableX+62],["标高范围",tableX+62,tableX+166],["级数",tableX+166,tableX+224],["转角",tableX+224,tableX+294],["内弯料/直弦",tableX+294,tableX+390],["外弯料/直弦",tableX+390,tableX+486],["每侧段数",tableX+486,tableX+560],["后接平台",tableX+560,tableX+tableW]].map(([label,left,right])=><FitText key={String(label)} x={Number(left)+8} y={tableY+rowH*.72} width={Number(right)-Number(left)-14} value={String(label)} className="support-table-head" fontSize={Math.min(7,rowH*.52)}/>)}
    {stair.flights.map((flight,index)=>{const y=tableY+rowH*(index+1)+rowH*.72,fontSize=Math.min(7.5,rowH*.55),cells:[string|number,number,number][]=[[flight.id,tableX,tableX+62],[`${flight.startElevation.toFixed(0)}~${flight.endElevation.toFixed(0)}`,tableX+62,tableX+166],[flight.stepCount,tableX+166,tableX+224],[`${Math.abs(flight.angleRad*180/Math.PI).toFixed(2)}°`,tableX+224,tableX+294],[`${flight.innerPieceLength.toFixed(0)}/${flight.innerStraightPieceLength.toFixed(0)}`,tableX+294,tableX+390],[`${flight.outerPieceLength.toFixed(0)}/${flight.outerStraightPieceLength.toFixed(0)}`,tableX+390,tableX+486],[flight.stockSegmentCount,tableX+486,tableX+560],[index<stair.platforms.length?stair.platforms[index].id:"顶平台",tableX+560,tableX+tableW]];return <g key={flight.id}>{cells.map(([value,left,right],cell)=><FitText key={cell} x={left+8} y={y} width={right-left-14} value={value} className="support-table-text" fontSize={fontSize}/>)}</g>})}
    <text x="50" y={tableY+tableH+16} className="note">表内“弯料/直弦”为每小段长度：前者用于滚弯螺旋，后者用于不弯曲的空间直段拼接。平台净尺寸 {model.stair.width} × {model.stair.platformLength??1200}。</text><text x="50" y={tableY+tableH+34} className="note warn">中心线净尺寸不含端切、接头和焊缩余量；平台梁、支撑型钢、罐壁垫板及焊缝必须验算局部应力、活荷载和风振。</text>
  </svg><TitleBlock model={model} title="外侧螺旋楼梯详图"/></div></div>;
}

export function Elevation({model}:{model:TankModel}){
  const x=210,w=360,y=335,h=235,rise=55,course=h/model.shell.courseCount;
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>储罐总装立面图</b><span>比例 AUTO · 单位 mm</span></div><svg viewBox="0 0 760 430" className="engineering-svg"><path d={`M ${x} ${y} L ${x} ${y-h} L ${x+w} ${y-h} L ${x+w} ${y} Z`} className="outline"/>{Array.from({length:model.shell.courseCount-1},(_,i)=><line key={i} x1={x} x2={x+w} y1={y-course*(i+1)} y2={y-course*(i+1)} className="weld"/>)}<path d={`M ${x} ${y-h} L ${x+w/2} ${y-h-rise} L ${x+w} ${y-h}`} className="outline"/><line x1={x+w+70} y1={y} x2={x+w+70} y2={y-h-rise} className="dim"/><text x={x+w+84} y={y-h/2} className="dimtext">{(model.shellHeight+model.roof.rise).toFixed(0)}</text><line x1={x} y1={y+30} x2={x+w} y2={y+30} className="dim"/><text x={x+w/2-36} y={y+49} className="dimtext">Ø{model.diameter.toFixed(0)}</text><path d={`M ${x+w+20} ${y} L ${x+w+90} ${y-h*.92}`} className="stair"/><text x="64" y="76" className="note strong">EL +{((model.shellHeight+model.roof.rise)/1000).toFixed(3)}</text><text x="64" y="98" className="note">顶盖坡度 1:{(model.diameter/2/model.roof.rise).toFixed(2)}</text></svg><TitleBlock model={model} title="储罐立面图"/></div></div>;
}

export function Plan({model}:{model:TankModel}){
  const cx=360,cy=208,r=145,courses=Math.max(1,Math.round(model.roof.radialCourseCount??1));
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>储罐平面定位图</b><span>角度基准：罐中心 / 正东 0°</span></div><svg viewBox="0 0 760 430" className="engineering-svg"><circle cx={cx} cy={cy} r={r} className="outline"/><circle cx={cx} cy={cy} r={model.roof.centerHoleRadius/model.diameter*2*r} className="outline"/>{Array.from({length:model.roof.plateCount},(_,i)=>{const a=i*2*Math.PI/model.roof.plateCount,p=polar(cx,cy,r,a);return <line key={i} x1={cx} y1={cy} x2={p[0]} y2={p[1]} className="weld"/>})}{Array.from({length:courses-1},(_,i)=><circle key={i} cx={cx} cy={cy} r={r*(i+1)/courses} className="weld"/>)}<line x1={cx-r-36} y1={cy} x2={cx+r+36} y2={cy} className="centerline"/><line x1={cx} y1={cy-r-36} x2={cx} y2={cy+r+36} className="centerline"/>{model.nozzles.map(n=>{const a=n.angle*Math.PI/180,p=polar(cx,cy,r+18,a);return <g key={n.id}><circle cx={p[0]} cy={p[1]} r="8" className="accessory"/><text x={p[0]+10} y={p[1]-8} className="dimtext">{n.id} DN{n.nominalDiameter}</text></g>})}<line x1={cx-r} y1={cy+r+45} x2={cx+r} y2={cy+r+45} className="dim"/><text x={cx-38} y={cy+r+65} className="dimtext">Ø{model.diameter}</text></svg><TitleBlock model={model} title="储罐平面定位图"/></div></div>;
}

export function ShellLayout({model}:{model:TankModel}){
  const parts=shellPanels(model),n=shellPlateCountPerCourse(model),w=620/n,h=280/model.shell.courseCount;
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>罐壁板展开排版图</b><span>纵缝逐圈错开 1/2 板幅</span></div><svg viewBox="0 0 760 430" className="engineering-svg"><g transform="translate(70 58)">{parts.map(p=>{const offset=p.course%2===0?w/2:0,x=((p.index-1)*w+offset)%620,y=280-p.course*h;return <g key={p.id}><rect x={x} y={y} width={w} height={h} className="plate"/><text x={x+5} y={y+h/2+3} className="plateid">{p.id}</text></g>})}</g><text x="70" y="35" className="dimtext">0° / 0 mm</text><text x="620" y="35" className="dimtext">360° / {(Math.PI*model.diameter).toFixed(1)} mm</text><text x="70" y="370" className="note">每圈 {n} 块 · 实际板长 {(Math.PI*model.diameter/n).toFixed(1)} mm · 圈高 {(model.shellHeight/model.shell.courseCount).toFixed(1)} mm</text></svg><TitleBlock model={model} title="罐壁板展开图"/></div></div>;
}

export function CapacityChart({model,level,setLevel}:{model:TankModel;level:number;setLevel:(v:number)=>void}){
  const rows=capacityTable(model,model.shellHeight/40),max=totalCapacity(model),x=70+level/model.shellHeight*610,y=335-(max?level/model.shellHeight:0)*260;
  return <div className="drawing-wrap"><div className="drawing-sheet"><div className="sheet-head"><b>液位—储量关系曲线</b><span>V(h) 与 dV/dh</span></div><svg viewBox="0 0 760 430" className="engineering-svg" onPointerMove={event=>{if(event.buttons){const box=event.currentTarget.getBoundingClientRect(),localX=(event.clientX-box.left)/box.width*760;setLevel(Math.max(0,Math.min(model.shellHeight,(localX-70)/610*model.shellHeight)))}}}><line x1="70" y1="335" x2="690" y2="335" className="axis"/><line x1="70" y1="335" x2="70" y2="65" className="axis"/><polyline points={rows.map(row=>`${70+row.level/model.shellHeight*610},${335-row.volume/max*260}`).join(" ")} className="curve"/><line x1={x} y1="335" x2={x} y2={y} className="cursor"/><circle cx={x} cy={y} r="6" className="cursorpoint"/><text x={Math.min(x+12,560)} y={Math.max(y-12,80)} className="note strong">液位 {(level/1000).toFixed(3)} m · 容积 {(max*level/model.shellHeight).toFixed(2)} m³</text><text x="65" y="365" className="dimtext">0</text><text x="650" y="365" className="dimtext">液位 {(model.shellHeight/1000).toFixed(1)} m</text><text x="18" y="76" className="dimtext">{max.toFixed(0)} m³</text><line x1="70" y1="250" x2="690" y2="250" className="derivative"/><text x="515" y="241" className="note">dV/dh = {(Math.PI*(model.diameter/2000)**2).toFixed(3)} m³/m</text></svg></div></div>;
}

export function BomTable({parts,selectedId,setSelectedId}:{parts:PartRecord[];selectedId:string;setSelectedId:(id:string)=>void}){
  return <div className="table-view"><div className="table-toolbar"><b>BOM 零件表</b><span>{parts.length} 个工程对象 · 点击行定位 3D 零件</span></div><div className="bom-scroll"><table><thead><tr><th>编号</th><th>零件</th><th>组件</th><th>厚度</th><th>尺寸</th><th>面积 m²</th><th>重量 kg</th></tr></thead><tbody>{parts.map(p=><tr key={p.id} className={p.id===selectedId?"selected":""} onClick={()=>setSelectedId(p.id)}><td><b>{p.id}</b></td><td>{p.name}</td><td>{p.component}</td><td>{p.thickness.toFixed(1)} mm</td><td>{p.dimensions}</td><td>{p.area.toFixed(3)}</td><td>{p.weight.toFixed(1)}</td></tr>)}</tbody></table></div></div>;
}
