"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import TankScene from "./TankScene";
import FabricationVisualizer from "./FabricationVisualizer";
import { BomTable, CapacityChart, Elevation, Plan, RoofDevelopment, RoofStructure, ShellLayout, StairDetail } from "./EngineeringViews";
import { defaultTankModel, type TankModel } from "../../src/tank/model";
import { buildBom, materialSummary } from "../../src/calculations/bom";
import { coneDevelopment } from "../../src/calculations/roof";
import { hydrostaticPressureKPa, totalCapacity, volumeAtLevel } from "../../src/calculations/capacity";
import { shellPlateCountPerCourse } from "../../src/calculations/shell";
import { stairGeometry } from "../../src/calculations/stair";
import { validateTank } from "../../src/validation/validate";
import { exportCapacityCsv, exportRoofPlateDxf, exportShellDxf, saveProject } from "../../src/export/downloads";
import { exportCurrentPage } from "../../src/export/pageExport";

const tabs=["3D 模型","下料排样","立面图","平面图","顶盖结构","顶盖展开","罐壁展开","楼梯详图","容量曲线","BOM"] as const;
type Tab=typeof tabs[number];

function NumField({label,value,unit,onChange,min=0,max,step=1}:{label:string;value:number;unit:string;onChange:(v:number)=>void;min?:number;max?:number;step?:number}){return <label className="field"><span>{label}</span><input aria-label={label} value={Number.isFinite(value)?value:0} min={min} max={max} step={step} type="number" onChange={e=>onChange(Number(e.target.value))}/><span>{unit}</span></label>}

export default function TankDesigner(){
  const [model,setModel]=useState<TankModel>(defaultTankModel); const [active,setActive]=useState<Tab>("3D 模型"); const [selectedId,setSelectedId]=useState("RP-08-01"); const [hovered,setHovered]=useState("");
  const [level,setLevel]=useState(model.shellHeight*.52); const [explosion,setExplosion]=useState(0); const [mode,setMode]=useState("真实模式"); const [showWelds,setShowWelds]=useState(true); const [exportOpen,setExportOpen]=useState(false); const [filling,setFilling]=useState(false); const inputRef=useRef<HTMLInputElement>(null);
  const bom=useMemo(()=>buildBom(model),[model]); const selected=bom.find(p=>p.id===selectedId); const roof=useMemo(()=>coneDevelopment(model),[model]); const summary=useMemo(()=>materialSummary(model),[model]); const warnings=useMemo(()=>validateTank(model),[model]); const stair=useMemo(()=>stairGeometry(model),[model]);
  const total=totalCapacity(model), volume=volumeAtLevel(model,level), mass=volume*model.liquid.density, fill=level/model.shellHeight*100;
  useEffect(()=>{if(!filling)return;const timer=window.setInterval(()=>setLevel(v=>v>=model.shellHeight?0:Math.min(model.shellHeight,v+model.shellHeight/180)),45);return()=>window.clearInterval(timer)},[filling,model.shellHeight]);
  const root=(patch:Partial<TankModel>)=>{setModel(m=>({...m,...patch}));if(typeof patch.shellHeight==="number")setLevel(v=>Math.min(v,patch.shellHeight!))};
  const shell=(patch:Partial<TankModel["shell"]>)=>setModel(m=>({...m,shell:{...m.shell,...patch}}));
  const roofPatch=(patch:Partial<TankModel["roof"]>)=>setModel(m=>({...m,roof:{...m.roof,...patch}}));
  const stairPatch=(patch:Partial<TankModel["stair"]>)=>setModel(m=>({...m,stair:{...m.stair,...patch}}));
  const loadProject=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result)) as TankModel;if(data.schemaVersion!==1)throw new Error();setModel(data);setLevel(data.shellHeight*.5)}catch{window.alert("项目文件无法读取或版本不兼容。")}};reader.readAsText(file)};
  const addNozzle=()=>setModel(m=>({...m,nozzles:[...m.nozzles,{id:`N${m.nozzles.length+1}`,nominalDiameter:200,elevation:1500,angle:(m.nozzles.length*90)%360,projection:450,service:"新接管"}]}));
  const exportCurrent=()=>{setExportOpen(false);if(active==="顶盖展开")exportRoofPlateDxf(model,selectedId.startsWith("RP-")?selectedId:"RP-01-01");else if(active==="罐壁展开")exportShellDxf(model);else exportCapacityCsv(model,100)};
  const exportPage=async(format:"png"|"pdf")=>{setExportOpen(false);try{await exportCurrentPage(format,model.project.name,active)}catch(error){window.alert(error instanceof Error?error.message:"导出失败，请重试。");}};
  return <main className="app">
    <header className="topbar"><div className="brand"><span className="brandmark"/><div><strong>TankWorks · 储罐设计器</strong><small>PARAMETRIC TANK ENGINEERING</small></div></div><div className="project-pill"><span>项目</span><b>{model.project.name}</b><i>REV {model.project.revision}</i></div><button className="top-action" onClick={()=>{setModel(defaultTankModel);setLevel(defaultTankModel.shellHeight*.52)}}>新建</button><button className="top-action" onClick={()=>saveProject(model)}>保存项目</button><button className="top-action" onClick={()=>inputRef.current?.click()}>导入</button><input ref={inputRef} hidden type="file" accept=".json,.tank.json" onChange={e=>loadProject(e.target.files?.[0])}/><div className="export-wrap"><button className="top-action primary" onClick={()=>setExportOpen(v=>!v)}>导出 ▾</button>{exportOpen&&<div className="export-menu"><button onClick={()=>exportPage("png")}>当前页面 PNG</button><button onClick={()=>exportPage("pdf")}>当前页面 PDF</button><span className="export-separator"/><button onClick={exportCurrent}>导出当前图 / 数据</button><button onClick={()=>exportRoofPlateDxf(model,selectedId.startsWith("RP-")?selectedId:"RP-01-01")}>梯形顶板 DXF</button><button onClick={()=>exportShellDxf(model)}>罐壁展开 DXF</button><button onClick={()=>exportCapacityCsv(model,100)}>容量表 CSV</button><button onClick={()=>saveProject(model)}>项目 JSON</button></div>}</div></header>
    <section className="workspace">
      <aside className="panel left"><div className="panel-title"><span>设计参数</span><span className="live-dot">实时联动</span></div>
        <details open><summary>储罐几何</summary><div className="section compact"><NumField label="储罐内径 D" value={model.diameter} unit="mm" min={5000} step={100} onChange={v=>root({diameter:v})}/><NumField label="罐壁高度 H" value={model.shellHeight} unit="mm" min={3000} step={100} onChange={v=>root({shellHeight:v})}/><NumField label="底部标高" value={model.bottomElevation} unit="mm" onChange={v=>root({bottomElevation:v})}/><NumField label="罐壁圈数" value={model.shell.courseCount} unit="圈" min={1} onChange={v=>shell({courseCount:Math.round(v)})}/><NumField label="钢板可用长度" value={model.shell.plateLength} unit="mm" onChange={v=>shell({plateLength:v})}/><NumField label="罐壁名义厚度" value={model.shell.nominalThickness} unit="mm" step={.5} onChange={v=>shell({nominalThickness:v})}/><NumField label="腐蚀裕量" value={model.shell.corrosionAllowance} unit="mm" step={.5} onChange={v=>shell({corrosionAllowance:v})}/></div></details>
        <details open><summary>锥形顶 / 分段顶板</summary><div className="section compact"><NumField label="中心升高 h" value={model.roof.rise} unit="mm" step={50} onChange={v=>roofPatch({rise:v})}/><NumField label="周向分瓣 N" value={model.roof.plateCount} unit="瓣" min={3} onChange={v=>roofPatch({plateCount:Math.round(v)})}/><NumField label="径向分段" value={model.roof.radialCourseCount??1} unit="段" min={1} onChange={v=>roofPatch({radialCourseCount:Math.round(v)})}/><NumField label="中心孔半径" value={model.roof.centerHoleRadius} unit="mm" onChange={v=>roofPatch({centerHoleRadius:v})}/><NumField label="顶板厚度" value={model.roof.thickness} unit="mm" step={.5} onChange={v=>roofPatch({thickness:v})}/><label className="select-field"><span>顶板接缝</span><select value={model.roof.seamType??"lap"} onChange={e=>roofPatch({seamType:e.target.value as "lap"|"butt"})}><option value="lap">单面搭接焊</option><option value="butt">对接焊</option></select></label>{(model.roof.seamType??"lap")==="lap"&&<NumField label="搭接宽度" value={model.roof.lapAllowance} unit="mm" min={0} step={5} onChange={v=>roofPatch({lapAllowance:v})}/>}<NumField label="焊接余量" value={model.roof.weldAllowance} unit="mm" onChange={v=>roofPatch({weldAllowance:v})}/><NumField label="边缘修整" value={model.roof.trimAllowance} unit="mm" onChange={v=>roofPatch({trimAllowance:v})}/><NumField label="库存板宽" value={model.roof.stockWidth} unit="mm" step={100} onChange={v=>roofPatch({stockWidth:v})}/><NumField label="库存板长" value={model.roof.stockLength} unit="mm" step={100} onChange={v=>roofPatch({stockLength:v})}/></div></details>
        <details open><summary>顶盖支撑结构</summary><div className="section compact"><NumField label="径向椽梁" value={model.roof.supportRafterCount??model.roof.plateCount} unit="根" min={4} onChange={v=>roofPatch({supportRafterCount:Math.round(v)})}/><NumField label="环向梁" value={model.roof.supportRingCount??0} unit="道" min={0} onChange={v=>roofPatch({supportRingCount:Math.round(v)})}/><NumField label="中心柱直径" value={model.roof.centerColumnDiameter??500} unit="mm" min={100} step={50} onChange={v=>roofPatch({centerColumnDiameter:v})}/><div className="mini-readout warn-readout">仅为结构布置示意；梁柱截面和节点必须按风、雪、检修及稳定荷载验算。</div></div></details>
        <details><summary>螺旋楼梯</summary><div className="section compact"><NumField label="楼梯宽度" value={model.stair.width} unit="mm" onChange={v=>stairPatch({width:v})}/><NumField label="目标踏步高" value={model.stair.targetRiser} unit="mm" onChange={v=>stairPatch({targetRiser:v})}/><NumField label="目标踏步深" value={model.stair.targetTread} unit="mm" onChange={v=>stairPatch({targetTread:v})}/><NumField label="罐壁净距" value={model.stair.clearance} unit="mm" onChange={v=>stairPatch({clearance:v})}/><NumField label="中间平台数量" value={model.stair.intermediatePlatformCount??2} unit="个" min={0} max={8} onChange={v=>stairPatch({intermediatePlatformCount:Math.max(0,Math.min(8,Math.round(v)))})}/><label className="select-field"><span>楼梯上升方向</span><select value={model.stair.direction??"ccw"} onChange={e=>stairPatch({direction:e.target.value as "cw"|"ccw"})}><option value="ccw">逆时针上升</option><option value="cw">顺时针上升</option></select></label><NumField label="休息平台长度" value={model.stair.platformLength??1200} unit="mm" min={model.stair.width} step={100} onChange={v=>stairPatch({platformLength:v})}/><NumField label="梯梁钢板高度" value={model.stair.stringerPlateDepth??250} unit="mm" min={100} step={10} onChange={v=>stairPatch({stringerPlateDepth:v})}/><NumField label="梯梁定尺" value={model.stair.stringerStockLength??6000} unit="mm" min={1000} step={500} onChange={v=>stairPatch({stringerStockLength:v})}/><NumField label="排样切割间距" value={model.stair.nestingGap??10} unit="mm" min={0} step={1} onChange={v=>stairPatch({nestingGap:v})}/><NumField label="支撑架间距" value={model.stair.supportSpacing??2000} unit="mm" min={500} step={100} onChange={v=>stairPatch({supportSpacing:v})}/><NumField label="扶手高度" value={model.stair.handrailHeight} unit="mm" onChange={v=>stairPatch({handrailHeight:v})}/><NumField label="起始角度" value={model.stair.startAngle} unit="°" onChange={v=>stairPatch({startAngle:v})}/><div className="mini-readout">{stair.flights.length} 个梯段 · {stair.platforms.length} 个中间平台 · {stair.direction===1?"逆时针":"顺时针"}上升 · 支撑 {stair.supportFrames.length} 榀</div></div></details>
        <details><summary>附件与介质</summary><div className="section compact"><button className="small-btn" onClick={addNozzle}>＋ 添加接管</button><label className="select-field"><span>介质</span><select value={model.liquid.name} onChange={e=>{const map:Record<string,number>={水:1000,柴油:830,原油:850};setModel(m=>({...m,liquid:{name:e.target.value,density:map[e.target.value]??m.liquid.density}}))}}><option>水</option><option>柴油</option><option>原油</option><option>自定义</option></select></label><NumField label="介质密度" value={model.liquid.density} unit="kg/m³" onChange={v=>setModel(m=>({...m,liquid:{...m.liquid,density:v}}))}/></div></details>
      </aside>
      <div className={`viewport ${showWelds?"show-welds":"hide-welds"}`}><div className="view-hud"><select value={mode} onChange={e=>setMode(e.target.value)}><option>真实模式</option><option>工程模式</option><option>顶盖骨架</option><option>X-Ray</option><option>预制模式</option></select>{!["3D 模型","下料排样","容量曲线","BOM"].includes(active)&&<button title="只控制工程图中的焊缝线，不改变结构和制造尺寸" className={`chip ${showWelds?"on":""}`} onClick={()=>setShowWelds(v=>!v)}>{showWelds?"隐藏焊缝线":"显示焊缝线"}</button>}{active==="3D 模型"&&<label className="explode" title="把顶盖板沿径向临时分开，便于查看每块板；这不是实际变形或施工尺寸"><span>顶板拆分查看</span><input aria-label="顶板拆分查看距离" type="range" min="0" max="1200" value={explosion} onChange={e=>setExplosion(+e.target.value)}/></label>}</div><div className="hover-tag">{hovered||selectedId||"单击零件查看工程数据"}</div>
        {active==="3D 模型"&&<TankScene model={model} selectedId={selectedId} setSelectedId={setSelectedId} setHovered={setHovered} level={level} explosion={explosion} mode={mode}/>} {active==="下料排样"&&<FabricationVisualizer model={model}/>} {active==="立面图"&&<Elevation model={model}/>} {active==="平面图"&&<Plan model={model}/>} {active==="顶盖结构"&&<RoofStructure model={model}/>} {active==="顶盖展开"&&<RoofDevelopment model={model} selectedId={selectedId}/>} {active==="罐壁展开"&&<ShellLayout model={model}/>} {active==="楼梯详图"&&<StairDetail model={model}/>} {active==="容量曲线"&&<CapacityChart model={model} level={level} setLevel={setLevel}/>} {active==="BOM"&&<BomTable parts={bom} selectedId={selectedId} setSelectedId={id=>{setSelectedId(id);setActive("3D 模型")}}/>}
      </div>
      <aside className="panel right"><div className="panel-title"><span>工程信息</span><span className="status-badge">PRELIMINARY</span></div><div className="status-card"><div className="eyebrow">PROJECT / DRAWING</div><div className="metric">{model.project.name} <small>REV {model.project.revision}</small></div><div className="drawing-no">{model.project.drawingNo}</div></div>
        {selected&&<div className="selection-card"><div className="part-code">{selected.id}</div><b>{selected.name}</b><div className="data-row"><span>材料</span><strong>{selected.material}</strong></div><div className="data-row"><span>厚度</span><strong>{selected.thickness.toFixed(1)} mm</strong></div><div className="data-row"><span>尺寸</span><strong>{selected.dimensions}</strong></div><div className="data-row"><span>面积</span><strong>{selected.area.toFixed(4)} m²</strong></div><div className="data-row"><span>重量</span><strong>{selected.weight.toFixed(1)} kg</strong></div>{selected.angle!==undefined&&<div className="data-row"><span>角度位置</span><strong>{selected.angle.toFixed(2)}°</strong></div>}<button className="outline-btn" onClick={()=>{if(selected.id.startsWith("RP-"))setActive("顶盖展开")}}>查看展开与下料尺寸 →</button></div>}
        <div className="section"><h3>容量与液位</h3><input className="level-slider" type="range" min="0" max={model.shellHeight} step="10" value={level} onChange={e=>setLevel(+e.target.value)}/><div className="level-actions"><button onClick={()=>setFilling(v=>!v)}>{filling?"暂停":"注液"}</button><button onClick={()=>{setFilling(false);setLevel(0)}}>排空</button></div><div className="data-grid"><div><span>液位</span><b>{(level/1000).toFixed(3)} m</b></div><div><span>充装率</span><b>{fill.toFixed(1)} %</b></div><div><span>当前容积</span><b>{volume.toFixed(1)} m³</b></div><div><span>剩余容量</span><b>{(total-volume).toFixed(1)} m³</b></div><div><span>介质质量</span><b>{(mass/1000).toFixed(1)} t</b></div><div><span>底部静压</span><b>{hydrostaticPressureKPa(model,level).toFixed(1)} kPa</b></div></div><p className="pressure-note">仅表示静液压力分布，非罐壁结构应力分析。</p></div>
        <div className="section"><h3>几何与材料</h3><div className="data-row"><span>公称容量</span><strong>{total.toFixed(1)} m³</strong></div><div className="data-row"><span>罐壁板 / 圈</span><strong>{shellPlateCountPerCourse(model)} 块</strong></div><div className="data-row"><span>锥面母线</span><strong>{roof.slantLength.toFixed(1)} mm</strong></div><div className="data-row"><span>单板展开角</span><strong>{(roof.plateAngleRad*180/Math.PI).toFixed(4)}°</strong></div><div className="data-row"><span>钢结构估重</span><strong>{(Object.values(summary).reduce((a,b)=>a+b,0)/1000).toFixed(2)} t</strong></div></div>
        <div className="alerts">{warnings.map((w,i)=><div key={i} className={`alert ${w.severity}`}><i>{w.severity==="error"?"×":w.severity==="warning"?"!":"i"}</i><span>{w.text}</span></div>)}</div>
      </aside>
    </section>
    <nav className="tabs">{tabs.map(x=><button key={x} onClick={()=>setActive(x)} className={`tab ${active===x?"active":""}`}>{x}{x==="BOM"&&<em>{bom.length}</em>}</button>)}<span className="tab-spacer"/><span className="footer-status">高精度模型 · SI/mm 内核　|　未经规范校核</span></nav>
  </main>;
}
